### ISSUE TITLE
`-d` to run `wf2 up` in the background

### ISSUE THREAD

**Issue by shakyShane** [WeareJH/wf2#16]
This will forward to `docker-compose up -d`

**Comment by shakyShane** [comment]
https://github.com/WeareJH/wf2/blob/aa2bc9475af6f0e91982012aaabfc1d5dd94c417/wf2_core/src/context.rs#L178

**Comment by JamelleG** [comment]
I know if we are to keep with the format of following `docker-compose` that having `wf2 up -d`  start in detached mode makes sense.
But I'm a massive fan of how workflow handles this by starting in detached mode by just running `wf2`, what's the reasoning behind doing it like this?

**Comment by shakyShane** [comment]
@JamelleG it's just a way to make debugging easier whilst people are trying it out - I'm happy to switch to `-d` by default once we're confident
