### ISSUE TITLE
Spaces in absolute path to project are not supported

### ISSUE THREAD

**Issue by annybs** [WeareJH/wf2#27]
```
Anny@crafters-companion-m2$ wf2 up
[wf2 info]: using wf2.yml
No such command: Companion/crafters_companion_m2/.wf2_default/docker_compose.yml
```

My absolute path being `.../Crafters Companion/...`

So I guess it just needs to be tweaked to escape spaces. For the meantime, as I suggested on Slack I've just concatenated the problem directory name to work around it 👍

**Comment by shakyShane** [comment]
@jflanaganuk can we revisit this, using `snailquote` maybe?
