### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by shakyShane** [WeareJH/wf2#43]

**Comment by mikeymike** [comment]
I think we can maybe close this off with the creation of the [Wiki](https://github.com/WeareJH/wf2/wiki), we know we need to actively build it up. 

@shakyShane what do you think?

**Comment by shakyShane** [comment]
@mikeymike yeah agreed

**Comment by shakyShane** [comment]
decided on in-code documentation with testable examples etc + auto publishing to docs.rs

https://docs.rs/wf2_core/0.28.1/wf2_core/
