### ISSUE TITLE
enforce time logging of yesterday when running wf2 up

### ISSUE THREAD

**Issue by jflanaganuk** [WeareJH/wf2#65]
Have a check when running
```
wf2 up
```
to see if you have logged time for yesterday as a reminder, we could either prompt the user and let them carry on with `wf2 up` or make it so they can't do it all until they book time.

It was suggested to also combine this check with the check to see if wf2 itself is up to date.

**Comment by shakyShane** [comment]
I don't think wf2 is the correct place for such tight integration (especially sime timelog will likely move to a separate tool)

More realistic would be a system of `triggers` where a user could prepend/append tasks if they so wish.

tl;dr - this is never happening 😂
