### ISSUE TITLE
[timelog][discussion] - Is Flex redundant?

### ISSUE THREAD

**Issue by jflanaganuk** [WeareJH/wf2#68]
The argument was that if we now have a tool that can extract the hours we have logged from jira, could we not use that instead of flex for flexitime logging, as it is effectively done automatically.

**Comment by mikeymike** [comment]
Making this a discussion point as there's a couple routes we could go down... 

1. Replace flex altogether, tricky but arguably somewhat possible. 
2. Integrate with flex directly (new API for flex ?)

**Comment by shakyShane** [comment]
in terms of wf2, no further timelogging features will be added - but this would be a good idea for a separate tool
